version = 1

exclude_patterns = [
 "example/**",
]

test_patterns = [
  "*test.*.*"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = [
  "github.com/burgesQ/webfmwk/v4",
  "github.com/burgesQ/webfmwk/v4/handler",
  "github.com/burgesQ/webfmwk/v4/webfmwktest",
]
  import_root = "github.com/burgesQ/webfmwk/v4"