{
  "version": 1,
  "analyzers": [
      {
          "meta": {
              "import_path": "gtihub.com/burgesQ/webfmwk/v3"
          },
          "name": "go",
          "enabled": true
      }
  ],
  "test_patterns": [
      "*test.*.*"
  ]
}
