linters-settings:
  # new settings
  cyclop:
    max-complexity: 15
    # package-average: 0.0
  funlen:
    lines: 90
    statements: 50
  gocyclo:
    min-complexity: 15
  gomoddirectives:
    # Allow local `replace` directives.
    replace-local: false
    # List of allowed `replace` directives.
    # replace-allow-list:
    #   - github.com/burgesQ/webfmwk/v5
  gomnd:
    checks: argument,case,condition,operation,return,assign
    # ignored-numbers: '0o666','0o755'
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - shadow
  misspell:
    locale: US
  maligned:
      # print struct with more effective memory layout or not, false by default
      suggest-new: true
  revive:
    ignore-generated-header: true
    severity: warning
    # enable-all-rules: true
  tagliatelle:
    case:
      rules:
        json: snake
  varnamelen:
    ignore-decls:
      - c context.Context
      - c webfmwk.Context
      - t testing.T
      - e error

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    # - exhaustivestruct ## lazy - none is def
    # - exhaustruct      ## lazy - none is def
    - exportloopref
    - forbidigo
    # - forcetypeassert
    - funlen
    - gci
    # - gocheckcompilerdirectives
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    # - godox ## lazy - should uncomment
    # - godot ## lazy - should uncomment
    - gocyclo
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - gosimple
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - ifshort
    - importas
    - interfacebloat
    # - ireturn ## to uncomment ..
    - lll
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    # - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - thelper
    - unconvert
    - usestdlibvars
    - unparam
    # - varnamelen ## to uncomment ...
    - wastedassign
    - whitespace
    # - wrapcheck ## to uncomment ...
    - wsl

    ### don't enable:
    # - ginkgolinter ## don't work
    # - golint   ## use revive
    # - maligned ## use fieldalignment
    # - nonamedreturns ## we name return on short func
    # - paralleltest
    # - testpackage ## we test internal stuff from pkg
    # - varcheck ## use unused


issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - lll
        - dupl
        - stylecheck
        - goerr113
        - forcetypeassert
        - gocritic
        - gosec
        # - govet
        - noctx
        - wsl
        # - cyclop
        # - unparam
        - revive

