name: GoBuild

on: [push]

jobs:
  build:

    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Go 1.11
      uses: actions/setup-go@v1
      with:
        go-version: 1.11
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Test
      run: |
        go test `go list ./... | grep -v example` -cover -v -short -coverprofile=coverage.out -covermode=atomic
        bash <(curl -s https://codecov.io/bash) -t 5abafd5f-9541-4c1b-962c-2fc05c89e2f0
