name: GoTest
on:
  pull_request:
  push:
    branches:
        - master
        - fasthttp
jobs:
  build:

    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.19
      uses: actions/setup-go@v1
      with:
        go-version: 1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Generate coverage report
      run: |
        go test -coverpkg ./... -coverprofile=coverage.txt -covermode=atomic -v -race

    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.txt
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true
